import type { Product, Order, Address } from "./types"

export const mockProducts: Product[] = [
  {
    id: "haw-pro-x1",
    name: "HawTec Pro X1 - Headphone Bluetooth Premium",
    description: "Headphone over-ear com cancelamento de ruido ativo, som Hi-Res e bateria de 40h.",
    longDescription: "O HawTec Pro X1 redefine a experiencia sonora com drivers personalizados de 40mm, cancelamento de ruido ativo adaptativo e codec LDAC para audio de alta resolucao.",
    price: 899.90,
    originalPrice: 1299.90,
    discountPercent: 31,
    images: ["/images/product-headphone.jpg", "/images/product-headphone-2.jpg", "/images/product-headphone-3.jpg", "/images/product-headphone-4.jpg"],
    rating: 4.7,
    reviewCount: 342,
    badge: "desconto",
    category: "Audio",
    brand: "HawTec",
    sku: "HAW-PRX1-BK",
    inStock: true,
    stockCount: 23,
    colors: [
      { name: "Preto", value: "#1a1a1a", available: true },
      { name: "Azul Marinho", value: "#1e3a5f", available: true },
      { name: "Prata", value: "#c0c0c0", available: true },
      { name: "Branco", value: "#f5f5f5", available: false },
    ],
    specs: [
      { label: "Driver", value: "40mm Neodimio" },
      { label: "Bluetooth", value: "5.3 (LDAC, AAC, SBC)" },
      { label: "Bateria", value: "40h (ANC ligado)" },
      { label: "Peso", value: "254g" },
    ],
    reviews: [
      { id: "r1", author: "Lucas M.", rating: 5, date: "2026-01-15", title: "Melhor headphone que ja tive", content: "Som absurdo, cancelamento de ruido impressionante.", verified: true },
      { id: "r2", author: "Ana P.", rating: 5, date: "2026-01-08", title: "Conforto incrivel", content: "Uso por horas sem nenhum desconforto.", verified: true },
    ],
  },
  {
    id: "haw-buds-s2",
    name: "HawTec Buds S2 - Fone TWS",
    description: "Fone true wireless com ANC hibrido, driver de 11mm e 32h de bateria total.",
    longDescription: "Os HawTec Buds S2 trazem som premium em formato compacto.",
    price: 449.90,
    originalPrice: 599.90,
    discountPercent: 25,
    images: ["/images/product-headphone.jpg"],
    rating: 4.5,
    reviewCount: 187,
    badge: "desconto",
    category: "Audio",
    brand: "HawTec",
    sku: "HAW-BDS2-BK",
    inStock: true,
    stockCount: 45,
    colors: [
      { name: "Preto", value: "#1a1a1a", available: true },
      { name: "Branco", value: "#f5f5f5", available: true },
    ],
    specs: [
      { label: "Driver", value: "11mm" },
      { label: "Bluetooth", value: "5.3" },
      { label: "Bateria", value: "32h total" },
      { label: "Peso", value: "5.2g por fone" },
    ],
    reviews: [],
  },
  {
    id: "haw-watch-ultra",
    name: "HawTec Watch Ultra",
    description: "Smartwatch com tela AMOLED 1.5\", GPS duplo e monitoramento avancado de saude.",
    longDescription: "O HawTec Watch Ultra combina design robusto com funcionalidades avancadas.",
    price: 1299.90,
    originalPrice: 1699.90,
    discountPercent: 24,
    images: ["/images/product-headphone.jpg"],
    rating: 4.8,
    reviewCount: 95,
    badge: "novo",
    category: "Wearables",
    brand: "HawTec",
    sku: "HAW-WU-TI",
    inStock: true,
    stockCount: 12,
    colors: [
      { name: "Titanio", value: "#8a8a8a", available: true },
      { name: "Preto", value: "#1a1a1a", available: true },
    ],
    specs: [
      { label: "Tela", value: "1.5\" AMOLED" },
      { label: "GPS", value: "Duplo (L1+L5)" },
      { label: "Bateria", value: "14 dias" },
      { label: "Resistencia", value: "10ATM" },
    ],
    reviews: [],
  },
  {
    id: "haw-speaker-360",
    name: "HawTec Speaker 360",
    description: "Caixa de som Bluetooth com som 360 graus, 24h de bateria e protecao IP67.",
    longDescription: "O Speaker 360 entrega som envolvente em qualquer direcao.",
    price: 599.90,
    images: ["/images/product-headphone.jpg"],
    rating: 4.6,
    reviewCount: 210,
    badge: "destaque",
    category: "Audio",
    brand: "HawTec",
    sku: "HAW-SP360-BK",
    inStock: true,
    stockCount: 30,
    colors: [
      { name: "Preto", value: "#1a1a1a", available: true },
      { name: "Azul", value: "#2563eb", available: true },
      { name: "Verde", value: "#16a34a", available: true },
    ],
    specs: [
      { label: "Potencia", value: "30W" },
      { label: "Bluetooth", value: "5.3" },
      { label: "Bateria", value: "24h" },
      { label: "Protecao", value: "IP67" },
    ],
    reviews: [],
  },
  {
    id: "haw-cam-4k",
    name: "HawTec Cam 4K Pro",
    description: "Webcam 4K com autofoco, microfone duplo e ring light integrada.",
    longDescription: "A HawTec Cam 4K Pro eleva o nivel das suas videochamadas.",
    price: 699.90,
    originalPrice: 899.90,
    discountPercent: 22,
    images: ["/images/product-headphone.jpg"],
    rating: 4.4,
    reviewCount: 78,
    badge: "desconto",
    category: "Perifericos",
    brand: "HawTec",
    sku: "HAW-CAM4K-BK",
    inStock: true,
    stockCount: 18,
    colors: [
      { name: "Preto", value: "#1a1a1a", available: true },
    ],
    specs: [
      { label: "Resolucao", value: "4K 30fps / 1080p 60fps" },
      { label: "FOV", value: "90 graus" },
      { label: "Microfone", value: "Duplo stereo" },
      { label: "Ring Light", value: "3 niveis" },
    ],
    reviews: [],
  },
  {
    id: "haw-kb-mech",
    name: "HawTec KB Mech TKL",
    description: "Teclado mecanico TKL com switches hot-swap, RGB per-key e corpo de aluminio.",
    longDescription: "O HawTec KB Mech TKL combina performance competitiva com estetica premium.",
    price: 549.90,
    images: ["/images/product-headphone.jpg"],
    rating: 4.9,
    reviewCount: 156,
    badge: "destaque",
    category: "Perifericos",
    brand: "HawTec",
    sku: "HAW-KB-TKL",
    inStock: true,
    stockCount: 35,
    colors: [
      { name: "Preto", value: "#1a1a1a", available: true },
      { name: "Branco", value: "#f5f5f5", available: true },
    ],
    specs: [
      { label: "Switches", value: "Hot-swap (3/5 pinos)" },
      { label: "Layout", value: "TKL (87 teclas)" },
      { label: "Corpo", value: "Aluminio CNC" },
      { label: "Conexao", value: "USB-C / Bluetooth / 2.4GHz" },
    ],
    reviews: [],
  },
]

export const mockAddresses: Address[] = [
  {
    id: "addr-1",
    label: "Casa",
    cep: "01001-000",
    street: "Rua Augusta",
    number: "1200",
    complement: "Apto 42",
    neighborhood: "Consolacao",
    city: "Sao Paulo",
    state: "SP",
    isDefault: true,
  },
  {
    id: "addr-2",
    label: "Trabalho",
    cep: "04543-011",
    street: "Av. Brigadeiro Faria Lima",
    number: "3477",
    complement: "15o andar",
    neighborhood: "Itaim Bibi",
    city: "Sao Paulo",
    state: "SP",
    isDefault: false,
  },
]

export const mockOrders: Order[] = [
  {
    id: "HWT-20260201-001",
    date: "2026-02-01",
    status: "entregue",
    items: [
      { productId: "haw-pro-x1", name: "HawTec Pro X1 - Headphone Bluetooth Premium", image: "/images/product-headphone.jpg", price: 899.90, quantity: 1, color: "Preto" },
    ],
    total: 899.90,
    shippingAddress: mockAddresses[0],
    paymentMethod: "Cartao de credito (final 4242)",
    trackingCode: "BR123456789HW",
  },
  {
    id: "HWT-20260115-002",
    date: "2026-01-15",
    status: "enviado",
    items: [
      { productId: "haw-buds-s2", name: "HawTec Buds S2 - Fone TWS", image: "/images/product-headphone.jpg", price: 449.90, quantity: 1, color: "Preto" },
      { productId: "haw-speaker-360", name: "HawTec Speaker 360", image: "/images/product-headphone.jpg", price: 599.90, quantity: 1, color: "Azul" },
    ],
    total: 1049.80,
    shippingAddress: mockAddresses[0],
    paymentMethod: "PIX",
    trackingCode: "BR987654321HW",
  },
  {
    id: "HWT-20260110-003",
    date: "2026-01-10",
    status: "processando",
    items: [
      { productId: "haw-watch-ultra", name: "HawTec Watch Ultra", image: "/images/product-headphone.jpg", price: 1299.90, quantity: 1, color: "Titanio" },
    ],
    total: 1299.90,
    shippingAddress: mockAddresses[1],
    paymentMethod: "Cartao de credito (final 1234)",
  },
  {
    id: "HWT-20251220-004",
    date: "2025-12-20",
    status: "cancelado",
    items: [
      { productId: "haw-cam-4k", name: "HawTec Cam 4K Pro", image: "/images/product-headphone.jpg", price: 699.90, quantity: 2, color: "Preto" },
    ],
    total: 1399.80,
    shippingAddress: mockAddresses[0],
    paymentMethod: "Boleto",
  },
]

export function getProductById(id: string): Product | undefined {
  return mockProducts.find((p) => p.id === id)
}

export function formatPrice(value: number) {
  return value.toLocaleString("pt-BR", {
    style: "currency",
    currency: "BRL",
  })
}
